name: Rebase check
description: Checks if rebase is needed
inputs:
  repo-url:
    description: Upstream repo URL
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-url }}
